In [1]:
import os 
import requests
from bs4 import BeautifulSoup
import json

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Comment out API keys to avoid running cells by accident

# api read key created at https://develop.purpleair.com/keys
api_read_key = "1A4A4B7E-BF7D-11EE-8616-42010A80000B"

# api write key created at https://develop.purpleair.com/keys
api_write_key = "FFAF2E2E-BF85-11EE-8616-42010A80000B"

In [3]:
# open variables json and assign to p_air_vars variable
with open('purple-air-variables.json') as f:
    p_air_vars = json.load(f)

# pull in the list of test sensors as sensor_test
sensor_test = p_air_vars['sensor_test']
sensor_test

[53, 77, 81, 443, 820]

In [4]:
# create function to pull all data from a sensor
def pull_sensor_data(sensor_id, p_air_READ_API_key):
    url = f"https://api.purpleair.com/v1/sensors/{sensor_id}"
    headers = {
        "X-API-Key": p_air_READ_API_key
        }
    
    sensor_response = requests.get(url, headers=headers)
    sensor_response_json = sensor_response.json()
    sensor_data = sensor_response_json.get('sensor')
    return sensor_data

In [5]:
list_of_test_sensors = []

for sensor in sensor_test:
    sensor_data = pull_sensor_data(sensor, api_read_key)
    list_of_test_sensors.append(sensor_data)

In [6]:
sample_sensor_df = pd.DataFrame(list_of_test_sensors)
sample_sensor_df

,sensor_index,last_modified,date_created,last_seen,private,is_owner,name,icon,location_type,model,...,5.0_um_count_b,10.0_um_count_b,pm1.0_cf_1_b,pm1.0_atm_b,pm2.5_atm_b,pm2.5_cf_1_b,pm10.0_atm_b,pm10.0_cf_1_b,stats_b,altitude
0,53,1520025982,1454548891,1707077195,0,0,Lakeshore,0,0,UNKNOWN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,77,1575074907,1456896339,1707077203,0,0,Sunnyside,0,0,PA-I,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,81,1465680292,1465657200,1707077203,0,0,Sherwood Hills 2,0,0,UNKNOWN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,443,1559966508,1478491864,1707077121,0,0,Weber-Morgan Health Department P1,0,0,PA-II,...,0.0,0.0,6.21,6.21,6.44,6.44,6.44,6.44,"{'pm2.5': 6.4, 'pm2.5_10minute': 7.0, 'pm2.5_3...",NaN
4,820,1575003401,1483643179,1707077255,0,0,Granite Basement,0,1,PA-II,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,"{'pm2.5': 0.0, 'pm2.5_10minute': 0.0, 'pm2.5_3...",5131.0

In [7]:
sample_sensor_df['last_modified'] = pd.to_datetime(sample_sensor_df['last_modified'], unit='s')
sample_sensor_df['date_created'] = pd.to_datetime(sample_sensor_df['date_created'], unit='s')
sample_sensor_df['last_seen'] = pd.to_datetime(sample_sensor_df['last_seen'], unit='s')

In [8]:
# commented out below, .csv exists in repo after first run, no longer needed

#sample_sensor_df.to_csv("sample_sensors.csv")

# Use all sensor data below

In [9]:
# pull in the list of ALL SLC sensors as slc_sensor_list
slc_sensor_list = p_air_vars['slc_sensor_list']

In [10]:
## EXPENSIVE cell. Pulls all 100+ columns for all 600+ sensors in SLC, outdoor and indoor
## The results are saved to slc_sensor_data_20240130.csv

# pull all SLC sensors into a list
# Cost of cell: 95480
# Time to run: 4 minutes

#list_of_slc_sensors = []

#for sensor in slc_sensor_list:
#    sensor_data = pull_sensor_data(sensor, api_read_key)
#    list_of_slc_sensors.append(sensor_data)

In [11]:
#slc_sensors_df = pd.DataFrame(list_of_slc_sensors)
#slc_sensors_df.to_csv('slc_sensor_data_20240130.csv')

In [12]:
# read in SLC sensor data from 1/30/24 snapshot
slc_sensor_eda = pd.read_csv('slc_sensor_data_20240130.csv')

In [13]:
slc_sensor_eda.describe()

,Unnamed: 0,sensor_index,last_modified,date_created,last_seen,private,is_owner,icon,location_type,led_brightness,...,pm2.5_cf_1_b,pm10.0_atm_b,pm10.0_cf_1_b,altitude,ozone1,humidity_b,temperature_b,pressure_b,voc,voc_b
count,616.000000,616.00000,6.160000e+02,6.160000e+02,6.160000e+02,616.0,616.0,616.0,616.000000,616.000000,...,487.000000,487.000000,487.000000,605.000000,1.0,56.000000,56.000000,56.000000,56.000000,56.000000
mean,307.500000,72891.12013,1.619314e+09,1.586838e+09,1.706636e+09,0.0,0.0,0.0,0.258117,35.357143,...,197.918234,140.514045,200.471335,4932.745455,145.0,25.482143,72.482143,856.775893,117.473214,117.477500
std,177.968162,60211.10269,4.582785e+07,5.573370e+07,4.218151e+04,0.0,0.0,0.0,0.437954,7.914321,...,934.066822,621.099381,933.626790,796.948542,NaN,10.421989,14.322254,20.808866,113.629944,113.626979
min,0.000000,53.00000,1.465680e+09,1.454549e+09,1.706164e+09,0.0,0.0,0.0,0.000000,5.000000,...,0.000000,0.000000,0.000000,4219.000000,145.0,11.000000,43.000000,798.910000,50.000000,50.000000
25%,153.750000,16260.00000,1.575398e+09,1.537884e+09,1.706641e+09,0.0,0.0,0.0,0.000000,35.000000,...,6.035000,7.200000,7.200000,4418.000000,145.0,18.000000,61.000000,849.665000,56.925000,56.922500
50%,307.500000,49683.00000,1.626983e+09,1.583598e+09,1.706641e+09,0.0,0.0,0.0,0.000000,35.000000,...,21.020000,23.050000,23.050000,4652.000000,145.0,24.500000,70.000000,863.955000,69.250000,69.250000
75%,461.250000,122074.50000,1.647643e+09,1.629497e+09,1.706641e+09,0.0,0.0,0.0,1.000000,35.000000,...,32.060000,35.335000,35.335000,5075.000000,145.0,29.000000,86.000000,869.992500,114.550000,114.540000
max,615.000000,208783.00000,1.706563e+09,1.703862e+09,1.706641e+09,0.0,0.0,0.0,1.000000,100.000000,...,6091.400000,4060.250000,6091.400000,8804.000000,145.0,65.000000,93.000000,880.020000,532.400000,532.370000

In [14]:
slc_sensor_eda.nunique()

Unnamed: 0       616
sensor_index     616
last_modified    616
date_created     616
last_seen        278
                ...
humidity_b        27
temperature_b     33
pressure_b        55
voc               53
voc_b             54
Length: 110, dtype: int64

In [15]:
# look at value counts for each column
# skip the first two columns since we know they'll all be unique
for column in slc_sensor_eda.columns[2:]:
    value_counts = slc_sensor_eda[column].value_counts()
    print(f'Column: {column}\n{value_counts}\n')

Column: last_modified
1520025982    1
1630852908    1
1629328369    1
1631251784    1
1631251712    1
             ..
1616983651    1
1548026904    1
1575088844    1
1575004554    1
1706498344    1
Name: last_modified, Length: 616, dtype: int64

Column: date_created
1454548891    1
1625008888    1
1624396549    1
1624482883    1
1624482885    1
             ..
1547074682    1
1547228302    1
1547232395    1
1547745418    1
1703862440    1
Name: date_created, Length: 616, dtype: int64

Column: last_seen
1706641222    9
1706641173    7
1706641183    7
1706641257    7
1706641272    7
             ..
1706641121    1
1706641041    1
1706641178    1
1706641202    1
1706641396    1
Name: last_seen, Length: 278, dtype: int64

Column: private
0    616
Name: private, dtype: int64

Column: is_owner
0    616
Name: is_owner, dtype: int64

Column: name
Home                  3
Wasatch Hollow        2
Riverton              2
Buckboard             2
Payson Utah           2
                     ..
Bonneville Academy    1
OV_DurfeeCreek        1
Oaks                  1
Kaysville             1
JCs house             1
Name: name, Length: 602, dtype: int64

Column: icon
0    616
Name: icon, dtype: int64

Column: location_type
0    457
1    159
Name: location_type, dtype: int64

Column: model
PA-II         368
PA-I          114
PA-II-SD       74
PA-II-FLEX     45
PA-I-LED       13
UNKNOWN         2
Name: model, dtype: int64

Column: hardware
2.0+BME280+PMSX003-B+PMSX003-A                                   324
2.0+BME280+PMSX003-A                                             111
2.0+OPENLOG+NO-DISK+DS3231+BME280+PMSX003-B+PMSX003-A             27
2.0+1M+BME280+PMSX003-B+PMSX003-A                                 25
2.0+PMSX003-B+PMSX003-A                                           18
2.0+OPENLOG+15476 MB+DS3231+BME280+PMSX003-B+PMSX003-A            14
3.0+BME68X+KX122+PMSX003-A                                        12
3.0+OPENLOG+NO-DISK+RV3028+BME68X+KX122+PMSX003-A+PMSX003-B        9
3.0+RV3028+BME68X+KX122+PMSX003-A+PMSX003-B                        9
3.0+RV3028+BME68X+PMSX003-A+PMSX003-B                              8
3.0+DS3231+BME280+BME68X+PMSX003-A+PMSX003-B                       5
2.0+OPENLOG+31037 MB+DS3231+BME280+PMSX003-B+PMSX003-A             5
2.0+OPENLOG+15931 MB+DS3231+BME280+PMSX003-B+PMSX003-A             5
3.0+OPENLOG+NO-DISK+RV3028+BME68X+PMSX003-A+PMSX003-B              5
2.0+OPENLOG+15980 MB+DS3231+BME280+PMSX003-B+PMSX003-A             4
2.0+OPENLOG+15802 MB+DS3231+BME280+PMSX003-B+PMSX003-A             3
2.0+OPENLOG+15833 MB+DS3231+BME280+PMSX003-B+PMSX003-A             3
2.0+OPENLOG+15485 MB+DS3231+BME280+PMSX003-B+PMSX003-A             3
2.0+OPENLOG+15560 MB+DS3231+BME280+PMSX003-B+PMSX003-A             2
3.0+PMSX003-A+PMSX003-B                                            2
2.0+DS3231+BME280+PMSX003-B+PMSX003-A                              2
2.0+OPENLOG+NO-DISK+DS3231+PMSX003-B+PMSX003-A                     2
1.0+1M+PMSX003-O                                                   2
3.0+OPENLOG+31954 MB+RV3028+BME68X+PMSX003-A+PMSX003-B             1
3.0+OPENLOG+31037 MB+RV3028+BME68X+PMSX003-A+PMSX003-B             1
2.0+OPENLOG+31954 MB+DS3231+BME280+PMSX003-B+PMSX003-A             1
3.0+BME280+BME68X+PMSX003-A                                        1
3.0+OPENLOG+31037 MB+RV3028+BME280+BME68X+PMSX003-A+PMSX003-B      1
3.0+OPENLOG+NO-DISK+DS3231+BME280+BME68X+PMSX003-A+PMSX003-B       1
2.0+BME280+BME68X+PMSX003-A                                        1
2.0+OPENLOG+15476 MB+PMSX003-B+PMSX003-A                           1
2.0+PMSX003-A                                                      1
3.0+DS3231+BME280+BME68X+PMSX003-A-R+PMSX003-B                     1
2.0+1M+PMSX003-A                                                   1
3.0+DS3231+PMSX003-A+PMSX003-B                                     1
2.0+OPENLOG+31914 MB+DS3231+BME280+PMSX003-B+PMSX003-A             1
2.0+OPENLOG+15836 MB+DS3231+BME280+PMSX003-B+PMSX003-A             1
2.0+1M+PMSX003-B+PMSX003-A                                         1
3.0+OPENLOG+NO-DISK+BME68X+KX122+PMSX003-A+PMSX003-B               1
Name: hardware, dtype: int64

Column: led_brightness
35     582
5        8
50       8
100      6
25       5
15       4
60       2
65       1
Name: led_brightness, dtype: int64

Column: firmware_version
7.02     529
7.04      58
6.06b     29
Name: firmware_version, dtype: int64

Column: rssi
-72    25
-70    23
-67    23
-62    21
-61    21
       ..
-92     1
-29     1
-89     1
-35     1
-96     1
Name: rssi, Length: 69, dtype: int64

Column: uptime
62098    14
62099    11
62115     7
62117     6
62097     6
         ..
9185      1
9895      1
28983     1
62683     1
915       1
Name: uptime, Length: 540, dtype: int64

Column: pa_latency
238.0     12
234.0      9
281.0      8
231.0      8
252.0      8
          ..
523.0      1
2281.0     1
703.0      1
465.0      1
485.0      1
Name: pa_latency, Length: 309, dtype: int64

Column: memory
15728    24
15936    23
15696    22
16104    20
15704    20
         ..
15232     1
15408     1
15520     1
16032     1
5752      1
Name: memory, Length: 171, dtype: int64

Column: position_rating
5    528
0     62
4      9
3      9
1      5
2      3
Name: position_rating, dtype: int64

Column: latitude
40.713238    2
40.681170    2
40.663070    2
40.246742    1
40.211560    1
            ..
41.384926    1
40.778870    1
41.024460    1
40.723434    1
40.761765    1
Name: latitude, Length: 613, dtype: int64

Column: longitude
-111.886010    2
-111.847490    2
-111.791480    2
-111.826485    2
-111.479340    2
              ..
-111.924194    1
-112.323530    1
-111.900770    1
-111.757520    1
-111.594680    1
Name: longitude, Length: 609, dtype: int64

Column: channel_state
3    487
1    129
Name: channel_state, dtype: int64

Column: channel_flags
0    547
2     35
1     34
Name: channel_flags, dtype: int64

Column: channel_flags_manual
0    591
1     17
2      8
Name: channel_flags_manual, dtype: int64

Column: channel_flags_auto
0    558
2     34
1     24
Name: channel_flags_auto, dtype: int64

Column: confidence
100    370
30     129
0       46
80      10
97       4
98       3
82       3
1        3
94       3
2        2
84       2
96       2
83       2
92       2
85       2
18       2
9        2
60       2
77       2
99       2
8        1
48       1
66       1
72       1
63       1
37       1
89       1
95       1
54       1
40       1
3        1
79       1
33       1
7        1
6        1
91       1
57       1
36       1
87       1
61       1
69       1
73       1
52       1
Name: confidence, dtype: int64

Column: analog_input
0.02    163
0.00    120
0.01    120
0.03     76
0.04     54
0.05     44
0.06     15
0.07      4
0.08      4
0.09      2
0.60      2
0.97      2
0.32      1
1.37      1
1.67      1
0.92      1
0.50      1
0.87      1
1.41      1
0.59      1
4.87      1
0.46      1
Name: analog_input, dtype: int64

Column: pm1.0
0.0     108
0.2      15
0.1       9
2.9       7
0.8       7
       ...
22.5      1
27.5      1
24.5      1
25.0      1
13.3      1
Name: pm1.0, Length: 233, dtype: int64

Column: pm1.0_a
0.0     104
0.2      11
0.1       9
14.2      8
0.3       8
       ...
11.7      1
27.5      1
7.8       1
9.6       1
2.8       1
Name: pm1.0_a, Length: 239, dtype: int64

Column: pm2.5
0.0     70
0.1     11
0.2     11
0.4      9
1.0      8
        ..
4.6      1
33.6     1
35.3     1
18.8     1
14.5     1
Name: pm2.5, Length: 297, dtype: int64

Column: pm2.5_a
0.0     70
0.2     11
0.4      8
0.1      8
1.0      7
        ..
22.9     1
31.1     1
35.2     1
34.4     1
14.0     1
Name: pm2.5_a, Length: 298, dtype: int64

Column: pm2.5_alt
0.0     20
0.4     16
0.6     13
0.3     13
0.5     12
        ..
27.6     1
3.9      1
13.1     1
18.3     1
8.7      1
Name: pm2.5_alt, Length: 231, dtype: int64

Column: pm2.5_alt_a
0.0     21
0.4     16
0.9     14
0.3     13
0.5     12
        ..
17.5     1
26.8     1
10.4     1
8.4      1
8.5      1
Name: pm2.5_alt_a, Length: 232, dtype: int64

Column: pm10.0
0.0     55
0.4     13
0.2     12
0.1     11
0.3      8
        ..
45.8     1
25.5     1
8.6      1
30.1     1
16.9     1
Name: pm10.0, Length: 319, dtype: int64

Column: pm10.0_a
0.0     54
0.4     11
0.1     11
0.2      9
0.3      9
        ..
40.8     1
44.1     1
47.4     1
11.6     1
21.7     1
Name: pm10.0_a, Length: 336, dtype: int64

Column: scattering_coefficient
1.7     6
2.0     6
1.3     6
1.6     5
0.9     5
       ..
11.1    1
43.6    1
4.5     1
38.5    1
28.4    1
Name: scattering_coefficient, Length: 375, dtype: int64

Column: scattering_coefficient_a
1.6     6
2.8     6
1.3     5
3.2     5
2.0     5
       ..
29.0    1
56.7    1
59.4    1
38.8    1
29.4    1
Name: scattering_coefficient_a, Length: 383, dtype: int64

Column: deciviews
17.0    8
2.0     7
15.9    7
1.7     6
18.3    6
       ..
15.6    1
38.8    1
11.7    1
0.3     1
14.8    1
Name: deciviews, Length: 231, dtype: int64

Column: deciviews_a
17.0    8
20.8    7
17.4    7
19.7    7
16.8    6
       ..
10.5    1
9.5     1
8.5     1
1.3     1
22.0    1
Name: deciviews_a, Length: 237, dtype: int64

Column: visual_range
79.6     4
40.1     4
41.4     3
41.1     3
48.5     3
        ..
169.2    1
48.9     1
371.9    1
239.8    1
88.5     1
Name: visual_range, Length: 474, dtype: int64

Column: visual_range_a
41.3     4
48.7     3
62.4     3
345.3    3
289.4    2
        ..
182.9    1
35.6     1
67.9     1
100.2    1
86.2     1
Name: visual_range_a, Length: 473, dtype: int64

Column: 0.3_um_count
0       15
258      3
166      3
2513     2
697      2
        ..
743      1
3872     1
27       1
348      1
126      1
Name: 0.3_um_count, Length: 558, dtype: int64

Column: 0.3_um_count_a
0       16
122      3
72       3
255      2
159      2
        ..
27       1
348      1
561      1
1918     1
1958     1
Name: 0.3_um_count_a, Length: 562, dtype: int64

Column: 0.5_um_count
0       16
61       6
16       5
33       4
8        4
        ..
531      1
1521     1
596      1
6687     1
548      1
Name: 0.5_um_count, Length: 462, dtype: int64

Column: 0.5_um_count_a
0       17
16       5
18       5
61       4
41       4
        ..
876      1
1019     1
1601     1
431      1
558      1
Name: 0.5_um_count_a, Length: 464, dtype: int64

Column: 1.0_um_count
0      34
3      16
5      15
6      15
1      11
       ..
189     1
159     1
33      1
168     1
119     1
Name: 1.0_um_count, Length: 241, dtype: int64

Column: 1.0_um_count_a
0      33
5      17
3      15
6      13
2      10
       ..
112     1
282     1
103     1
105     1
191     1
Name: 1.0_um_count_a, Length: 235, dtype: int64

Column: 2.5_um_count
0     187
1      57
2      42
13     21
6      20
3      18
12     18
4      15
11     15
16     15
15     14
10     14
8      12
9      11
7      11
14     11
18     10
19     10
22      9
23      9
32      8
26      8
17      8
31      7
36      7
24      6
21      5
20      5
5       5
28      4
25      4
39      3
29      3
33      3
30      3
35      2
42      2
27      2
43      2
48      1
81      1
65      1
49      1
51      1
68      1
38      1
34      1
37      1
45      1
Name: 2.5_um_count, dtype: int64

Column: 2.5_um_count_a
0     184
1      52
2      37
3      27
10     21
13     18
4      17
11     17
7      16
15     15
8      14
6      13
14     13
19     11
20     10
5      10
9      10
12      9
24      9
22      8
16      8
18      8
27      7
17      7
30      7
21      6
23      5
25      5
28      5
31      5
39      4
35      4
34      3
26      3
33      3
29      3
37      3
43      3
42      2
32      2
46      2
36      2
52      1
48      1
68      1
65      1
44      1
47      1
45      1
38      1
Name: 2.5_um_count_a, dtype: int64

Column: 5.0_um_count
0      311
1       78
2       51
3       43
4       37
5       21
6       16
7       14
11       8
9        7
8        7
15       4
12       3
14       3
16       2
10       2
134      1
127      1
27       1
23       1
123      1
132      1
21       1
17       1
26       1
Name: 5.0_um_count, dtype: int64

Column: 5.0_um_count_a
0      294
1       88
2       61
3       53
6       24
4       22
5       19
7       11
8        7
9        6
15       5
11       4
10       3
12       2
21       2
131      2
22       2
20       2
17       1
16       1
18       1
13       1
124      1
23       1
121      1
27       1
14       1
Name: 5.0_um_count_a, dtype: int64

Column: 10.0_um_count
0      485
1       63
2       30
3       10
4        9
9        4
10       3
5        2
6        1
14       1
21       1
8        1
7        1
332      1
346      1
359      1
335      1
15       1
Name: 10.0_um_count, dtype: int64

Column: 10.0_um_count_a
0      469
1       71
2       33
3       17
4        8
6        3
8        2
351      1
338      1
364      1
21       1
334      1
15       1
10       1
9        1
18       1
5        1
7        1
13       1
20       1
Name: 10.0_um_count_a, dtype: int64

Column: pm1.0_cf_1
0.0     108
0.2      15
0.1       9
0.8       7
2.9       7
       ...
29.3      1
8.8       1
17.5      1
33.3      1
13.3      1
Name: pm1.0_cf_1, Length: 251, dtype: int64

Column: pm1.0_cf_1_a
0.00     97
0.21      4
0.04      3
2.33      3
0.28      3
         ..
11.61     1
2.89      1
16.66     1
0.72      1
10.44     1
Name: pm1.0_cf_1_a, Length: 468, dtype: int64

Column: pm1.0_atm
0.0     108
0.2      15
0.1       9
0.8       7
2.9       7
       ...
26.6      1
22.5      1
27.5      1
24.5      1
13.3      1
Name: pm1.0_atm, Length: 232, dtype: int64

Column: pm1.0_atm_a
0.00     97
0.21      4
0.28      3
0.04      3
0.02      3
         ..
18.83     1
1.09      1
12.20     1
16.47     1
10.44     1
Name: pm1.0_atm_a, Length: 468, dtype: int64

Column: pm2.5_atm
0.0     70
0.1     11
0.2     11
0.4      9
1.0      8
        ..
27.4     1
26.1     1
44.6     1
5.6      1
14.5     1
Name: pm2.5_atm, Length: 295, dtype: int64

Column: pm2.5_atm_a
0.00     58
0.04      6
0.02      3
4.40      3
0.20      3
         ..
43.28     1
3.27      1
0.11      1
36.96     1
13.95     1
Name: pm2.5_atm_a, Length: 514, dtype: int64

Column: pm2.5_cf_1
0.0     70
0.2     11
0.1     11
0.4      9
1.0      8
        ..
4.6      1
32.0     1
32.4     1
34.7     1
14.5     1
Name: pm2.5_cf_1, Length: 308, dtype: int64

Column: pm2.5_cf_1_a
0.00     58
0.04      6
0.02      3
0.20      3
4.40      3
         ..
0.76      1
17.93     1
51.54     1
3.27      1
13.95     1
Name: pm2.5_cf_1_a, Length: 512, dtype: int64

Column: pm10.0_atm
0.0     55
0.4     13
0.2     12
0.1     11
0.3      8
        ..
5.5      1
38.8     1
45.8     1
25.5     1
16.9     1
Name: pm10.0_atm, Length: 320, dtype: int64

Column: pm10.0_atm_a
0.00     47
0.41      4
1.35      3
0.10      3
0.53      3
         ..
19.00     1
54.42     1
3.45      1
52.12     1
0.09      1
Name: pm10.0_atm_a, Length: 516, dtype: int64

Column: pm10.0_cf_1
0.0     55
0.4     13
0.2     12
0.1     11
0.3      8
        ..
45.0     1
46.8     1
25.5     1
51.0     1
16.9     1
Name: pm10.0_cf_1, Length: 321, dtype: int64

Column: pm10.0_cf_1_a
0.00     47
0.41      4
1.35      3
18.76     3
0.53      3
         ..
3.45      1
56.61     1
26.65     1
17.25     1
0.09      1
Name: pm10.0_cf_1_a, Length: 515, dtype: int64

Column: primary_id_a
84144.0      1
1420451.0    1
1352022.0    1
1365296.0    1
1369585.0    1
            ..
658723.0     1
660357.0     1
663430.0     1
663544.0     1
2186572.0    1
Name: primary_id_a, Length: 586, dtype: int64

Column: primary_key_a
DYBYPI2LSK4QGFNM    1
0SJCDK4O5TIBANOJ    1
3U4GL9HHDG0L4QNA    1
OOOUEYZSMAYA8ODC    1
9H8UC9SQC9TW54KS    1
                   ..
C82DOU7P90GGFLG2    1
1STOMIECVC3TKPF9    1
9MRSLHP04ITHKZIP    1
NXBA5QKRILOB1KE6    1
JFB1W3HWRUNEVT52    1
Name: primary_key_a, Length: 616, dtype: int64

Column: primary_id_b
725391.0     1
1420453.0    1
1352024.0    1
1365298.0    1
1369587.0    1
            ..
658726.0     1
660359.0     1
663432.0     1
663546.0     1
2186576.0    1
Name: primary_id_b, Length: 586, dtype: int64

Column: primary_key_b
DGNHAFD7NZV9H2RZ    1
EGW6F3HW4YHGWUS3    1
89OG3T81LKIIMRA3    1
6JOQ4KWSS7ZRJCF7    1
93G4LF8M0TJ4MLRE    1
                   ..
19C47GAYDIE0N6KK    1
TTBGALVWEDVMYQU0    1
7HWE7SF7TQOYYOX3    1
57ZIOJ4LF4OH0HGE    1
G4R064HSLTRR8HM1    1
Name: primary_key_b, Length: 586, dtype: int64

Column: secondary_id_a
84145.0      1
1420452.0    1
1352023.0    1
1365297.0    1
1369586.0    1
            ..
658725.0     1
660358.0     1
663431.0     1
663545.0     1
2186574.0    1
Name: secondary_id_a, Length: 586, dtype: int64

Column: secondary_key_a
ITY12CRN3H8KPBJY    1
0QBWP6Y0M2I9A8ZB    1
QGNUSKA4MAWGM0N2    1
8AIN85QY754O6UOB    1
8FXPG94BQU3IIN2B    1
                   ..
QY6XFBJM2R831ZTU    1
4NH5ZIFKCCFPKUSH    1
0ER8CVM1KXTSA5TZ    1
AB1EHMXO2XUTMIVN    1
3EIGHRRBAFVVIPFA    1
Name: secondary_key_a, Length: 586, dtype: int64

Column: secondary_id_b
725392.0     1
1420454.0    1
1352026.0    1
1365299.0    1
1369588.0    1
            ..
658727.0     1
660360.0     1
663433.0     1
663547.0     1
2186578.0    1
Name: secondary_id_b, Length: 586, dtype: int64

Column: secondary_key_b
EB6SJL8KOR7K7WCA    1
95EAI8ESWOSPJFVZ    1
7GUDOPYWNCHJQ2R6    1
UNNQTQ31QNQQR1XX    1
6XO7G4XBXS9E5MX0    1
                   ..
5MJEK4LF5XSICJ6S    1
WUIG3JPKGTPKW451    1
04R25ESWXDV9UFSM    1
OGYBMH7DTICL1GTD    1
DPRV5NVMX1LB9LKN    1
Name: secondary_key_b, Length: 586, dtype: int64

Column: stats
{'pm2.5': 0.0, 'pm2.5_10minute': 0.0, 'pm2.5_30minute': 0.0, 'pm2.5_60minute': 0.0, 'pm2.5_6hour': 0.0, 'pm2.5_24hour': 0.0, 'pm2.5_1week': 0.0, 'time_stamp': 1706641157}           2
{'pm2.5': 0.6, 'pm2.5_10minute': 0.4, 'pm2.5_30minute': 0.2, 'pm2.5_60minute': 0.2, 'pm2.5_6hour': 0.4, 'pm2.5_24hour': 0.5, 'pm2.5_1week': 0.5, 'time_stamp': 1706641173}           1
{'pm2.5': 27.2, 'pm2.5_10minute': 29.8, 'pm2.5_30minute': 29.2, 'pm2.5_60minute': 26.0, 'pm2.5_6hour': 18.6, 'pm2.5_24hour': 14.1, 'pm2.5_1week': 7.1, 'time_stamp': 1706641116}     1
{'pm2.5': 4.9, 'pm2.5_10minute': 8.2, 'pm2.5_30minute': 18.2, 'pm2.5_60minute': 31.0, 'pm2.5_6hour': 26.0, 'pm2.5_24hour': 15.5, 'pm2.5_1week': 10.5, 'time_stamp': 1706641222}      1
{'pm2.5': 0.2, 'pm2.5_10minute': 0.1, 'pm2.5_30minute': 0.1, 'pm2.5_60minute': 0.0, 'pm2.5_6hour': 0.2, 'pm2.5_24hour': 0.3, 'pm2.5_1week': 0.8, 'time_stamp': 1706641222}           1
                                                                                                                                                                                    ..
{'pm2.5': 0.0, 'pm2.5_10minute': 0.0, 'pm2.5_30minute': 0.0, 'pm2.5_60minute': 0.2, 'pm2.5_6hour': 4.4, 'pm2.5_24hour': 4.6, 'pm2.5_1week': 3.8, 'time_stamp': 1706637895}           1
{'pm2.5': 29.7, 'pm2.5_10minute': 35.8, 'pm2.5_30minute': 39.5, 'pm2.5_60minute': 39.2, 'pm2.5_6hour': 30.6, 'pm2.5_24hour': 23.0, 'pm2.5_1week': 13.4, 'time_stamp': 1706641204}    1
{'pm2.5': 4.1, 'pm2.5_10minute': 3.7, 'pm2.5_30minute': 3.7, 'pm2.5_60minute': 3.2, 'pm2.5_6hour': 2.3, 'pm2.5_24hour': 1.9, 'pm2.5_1week': 1.7, 'time_stamp': 1706641202}           1
{'pm2.5': 30.7, 'pm2.5_10minute': 31.9, 'pm2.5_30minute': 33.4, 'pm2.5_60minute': 33.8, 'pm2.5_6hour': 28.2, 'pm2.5_24hour': 21.0, 'pm2.5_1week': 12.6, 'time_stamp': 1706641178}    1
{'pm2.5': 0.0, 'pm2.5_10minute': 0.0, 'pm2.5_30minute': 0.0, 'pm2.5_60minute': 0.0, 'pm2.5_6hour': 2.2, 'pm2.5_24hour': 5.3, 'pm2.5_1week': 1.6, 'time_stamp': 1706641272}           1
Name: stats, Length: 615, dtype: int64

Column: stats_a
{'pm2.5': 0.6, 'pm2.5_10minute': 0.4, 'pm2.5_30minute': 0.2, 'pm2.5_60minute': 0.2, 'pm2.5_6hour': 0.4, 'pm2.5_24hour': 0.5, 'pm2.5_1week': 0.5, 'time_stamp': 1706641173}           1
{'pm2.5': 15.6, 'pm2.5_10minute': 16.7, 'pm2.5_30minute': 17.2, 'pm2.5_60minute': 15.5, 'pm2.5_6hour': 8.8, 'pm2.5_24hour': 11.0, 'pm2.5_1week': 11.8, 'time_stamp': 1706641192}     1

In [16]:
slc_sensor_eda['last_modified'] = pd.to_datetime(slc_sensor_eda['last_modified'], unit='s')
slc_sensor_eda['date_created'] = pd.to_datetime(slc_sensor_eda['date_created'], unit='s')
slc_sensor_eda['last_seen'] = pd.to_datetime(slc_sensor_eda['last_seen'], unit='s')

slc_sensor_eda.head()

,Unnamed: 0,sensor_index,last_modified,date_created,last_seen,private,is_owner,name,icon,location_type,...,pm10.0_atm_b,pm10.0_cf_1_b,stats_b,altitude,ozone1,humidity_b,temperature_b,pressure_b,voc,voc_b
0,0,53,2018-03-02 21:26:22,2016-02-04 01:21:31,2024-01-30 18:59:33,0,0,Lakeshore,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,77,2019-11-30 00:48:27,2016-03-02 05:25:39,2024-01-30 18:59:30,0,0,Sunnyside,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,81,2016-06-11 21:24:52,2016-06-11 15:00:00,2024-01-30 18:59:22,0,0,Sherwood Hills 2,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,443,2019-06-08 04:01:48,2016-11-07 04:11:04,2024-01-30 18:58:00,0,0,Weber-Morgan Health Department P1,0,0,...,10.02,10.02,"{'pm2.5': 9.8, 'pm2.5_10minute': 7.8, 'pm2.5_3...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,459,2022-05-29 03:50:54,2016-11-07 18:32:48,2024-01-30 18:58:27,0,0,Flight Park North 2,0,0,...,7.50,7.50,"{'pm2.5': 6.8, 'pm2.5_10minute': 9.4, 'pm2.5_3...",5122.0,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
oldest_sensor = slc_sensor_eda['date_created'].min()
oldest_sensor

Timestamp('2016-02-04 01:21:31')